# Generated by Django 4.0.3 on 2022-04-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='featured_product',
            new_name='featured_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='collection',
            new_name='category',
        ),
    ]
