# Generated by Django 4.0.3 on 2022-04-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='portal.tag'),
            preserve_default=False,
        ),
    ]
