# Generated by Django 4.0.3 on 2022-04-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
